[package]
name = "rust-halide-tests"
version = "0.1.0"
edition = "2021"

#RUSTFLAGS="-Z sanitizer=address"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
